# Generated by Django 6.0.6 on 2026-06-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0004_videojuego_plataforma'),
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='juegos_favoritos',
            field=models.ManyToManyField(blank=True, to='juegos.videojuego'),
        ),
    ]
