# Generated by Django 6.0.5 on 2026-06-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='en_oferta',
            field=models.BooleanField(default=False),
        ),
    ]
