# Generated by Django 6.0.6 on 2026-06-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0003_categoria_videojuego_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='plataforma',
            field=models.CharField(choices=[('PC', 'PC'), ('PS5', 'PlayStation 5'), ('Xbox Series X', 'Xbox Series X'), ('Nintendo Switch', 'Nintendo Switch'), ('PS4', 'PlayStation 4'), ('Xbox One', 'Xbox One')], default='PC', max_length=50),
        ),
    ]
