# Generated by Django 6.0.6 on 2026-06-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0004_videojuego_plataforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='precio_oferta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
