# Generated by Django 6.0.6 on 2026-06-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0005_videojuego_precio_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='juegos/'),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='juegos/'),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='juegos/'),
        ),
    ]
