# Generated by Django 6.0.6 on 2026-06-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0007_compra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videojuego',
            old_name='imagen',
            new_name='portada',
        ),
    ]
