# Generated by Django 6.0.6 on 2026-06-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0008_rename_imagen_videojuego_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='plataforma',
            field=models.CharField(choices=[('PS5', 'PlayStation 5'), ('Xbox Series X', 'Xbox Series X'), ('Nintendo Switch', 'Nintendo Switch'), ('PS4', 'PlayStation 4'), ('Xbox One', 'Xbox One')], default='PS5', max_length=50),
        ),
    ]
