# Generated by Django 6.0.6 on 2026-06-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0010_alter_videojuego_plataforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='fecha_destacado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='fecha_oferta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='plataforma',
            field=models.CharField(choices=[('PS5', 'PlayStation 5'), ('Xbox Series X', 'Xbox Series X'), ('Nintendo Switch', 'Nintendo Switch'), ('PS4', 'PlayStation 4'), ('Xbox One', 'Xbox One'), ('Xbox Tresesenta', 'Xbox 360')], default='PS5', max_length=50),
        ),
    ]
