# Generated by Django 6.0.6 on 2026-06-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0011_videojuego_fecha_destacado_videojuego_fecha_oferta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
