# Generated by Django 6.0.6 on 2026-06-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0013_venta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
