# Generated by Django 6.0.6 on 2026-06-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0014_delete_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
